//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asasuzume.Assets.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asasuzume.Assets.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chii.
        /// </summary>
        public static string Chii {
            get {
                return ResourceManager.GetString("Chii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abortive Draw.
        /// </summary>
        public static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan.
        /// </summary>
        public static string Kan {
            get {
                return ResourceManager.GetString("Kan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pon.
        /// </summary>
        public static string Pon {
            get {
                return ResourceManager.GetString("Pon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riichi.
        /// </summary>
        public static string Riichi {
            get {
                return ResourceManager.GetString("Riichi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ron.
        /// </summary>
        public static string Ron {
            get {
                return ResourceManager.GetString("Ron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tsumo.
        /// </summary>
        public static string Tsumo {
            get {
                return ResourceManager.GetString("Tsumo", resourceCulture);
            }
        }
    }
}
